import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Button from "../components/Button";
import LoginForm from "../components/LoginForm";
import Modal from "../components/Modal";
import RegisterForm from "../components/RegisterForm";

// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.getAll"]);

  // const userMutation = trpc.useMutation(["register.execute"])

  // const onClick = () => {
  //   userMutation.mutate({ name: 'Juan Pedro', email: 'jppontverges@gmail.com' })
  // }

  const [isLoginModalOpen, setIsLoginModalOpen] = useState(false)
  const [isRegisterModalOpen, setIsRegisterModalOpen] = useState(false)

  const toggleLoginModal = () => {
    setIsLoginModalOpen(!isLoginModalOpen)
  }

  const toggleRegisterModal = () => {
    setIsRegisterModalOpen(!isRegisterModalOpen)
  }

  return (
    <>
      <Head>
        <title>Cacao Whatsapp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Cacao
        </h1>
        <div className="pt-3 mt-3 text-center">
          <Button onClick={toggleLoginModal} className={'w-[200px]'}>Log in</Button>
        </div>
        <div className="pt-3 mt-3 text-center">
          <Button onClick={toggleRegisterModal} className={'w-[200px]'}>Registrarme</Button>
        </div>
        {/* Modals */}
        <Modal title="Bienvenido" isOpen={isLoginModalOpen} toggleVisibility={toggleLoginModal} >
          <LoginForm toggleModalVisibility={toggleLoginModal} />
        </Modal>
        <Modal title="Registro" isOpen={isRegisterModalOpen} toggleVisibility={toggleRegisterModal}>
          <RegisterForm toggleModalVisibility={toggleRegisterModal} />
        </Modal>
      </main>
    </>
  );
};

export default Home;