import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Button from "../components/Button";
import Modal from "../components/Modal";
// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.getAll"]);

  // const userMutation = trpc.useMutation(["register.execute"])

  // const onClick = () => {
  //   userMutation.mutate({ name: 'Juan Pedro', email: 'jppontverges@gmail.com' })
  // }

  const [isLoginModalOpen, setIsLoginModalOpen] = useState(true)
  const [isRegisterModalOpen, setIsRegisterModalOpen] = useState(true)

  const toogleLoginModal = () => {
    setIsLoginModalOpen(!isLoginModalOpen)
  }

  const toogleRegisterModal = () => {
    setIsRegisterModalOpen(!isRegisterModalOpen)
  }

  return (
    <>
      <Head>
        <title>Cacao Whatsapp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Cacao
        </h1>
        <Modal isOpen={isLoginModalOpen} toogleVisibility={toogleLoginModal} />
        <Modal isOpen={isRegisterModalOpen} toogleVisibility={toogleRegisterModal} />
        <div className="pt-3 mt-3 text-center">
          <Button onClick={toogleLoginModal}>Iniciar sesión</Button>
        </div>
        <div className="pt-3 mt-3 text-center">
          <Button onClick={toogleRegisterModal}>Registrarme</Button>
        </div>
      </main>
    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
