import { GetServerSideProps, GetServerSidePropsContext } from "next";
import Head from "next/head";
import Dashboard from "../components/layouts/Dashboard";
import { getServerAuthSession } from "../server/common/get-server-auth-session";
import { NextPageWithLayout } from "./_app";
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from 'chart.js';
import { Pie } from 'react-chartjs-2';
import { trpc } from "../utils/trpc";
import { useSession } from "next-auth/react";
import Table from "../components/Table";
import { ColumnDef, getCoreRowModel, useReactTable } from "@tanstack/react-table";
import { ReactNode, useEffect, useState } from "react";
import dayjs from 'dayjs';

ChartJS.register(ArcElement, Tooltip, Legend);
const labels: any[] = [];

const chartData: { labels: any[]; datasets: any[] } = {
    labels,
    datasets: [{
        backgroundColor: [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)',
        ],
        borderColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)',
        ],
        borderWidth: 1,
        data: [],
    }],
};

type Customer = {
    fullName: string;
    phoneNumber: string;
    createdAt: Date;
}


const customerDefaultColumns: ColumnDef<Customer>[] = [
    {
        header: () => <span className="mr-2">Nombre completo</span>,
        cell: (info) => <span className="mr-2">{info.getValue() as ReactNode}</span>,
        accessorKey: 'fullName',
    },
    {
        header: () => <span className="mx-2">Número de Teléfono</span>,
        cell: (info) => <span className="mx-2">{info.getValue() as ReactNode}</span>,
        accessorKey: 'phoneNumber',
    },
    {
        header: () => <span className="mx-2">Capturado en</span>,
        cell: (info) => <span className="mx-2">{String(dayjs(info.getValue() as Date).format('DD/MM/YY')) as ReactNode}</span>,
        accessorKey: 'createdAt',
    },
]

const Reports: NextPageWithLayout = () => {
    const { data } = useSession();
    const userQuery = trpc.useQuery(["userRouter.getVenues", { id: data?.user?.id }]);
    const salesByProductQuery = trpc.useQuery(["reportRouter.sellsByProduct", { venueId: userQuery?.data?.venueId }]);
    const customerQuery = trpc.useQuery(["reportRouter.customersByVenueId", { venueId: userQuery.data?.venueId }]);
    const [customerColumns] = useState(() => [...customerDefaultColumns]);
    const [customers, setCustomers] = useState(() => customerQuery.data ? [...customerQuery.data] : []);
    useEffect(() => {
        if (customerQuery.data) {
            setCustomers(customerQuery.data);
        }
    }, [customerQuery.data])
    const customersTable = useReactTable({
        data: customers,
        columns: customerColumns,
        getCoreRowModel: getCoreRowModel(),
    })
    if (!salesByProductQuery.data) return <>Loading...</>;
    if (!chartData.datasets[0].data.length) {
        salesByProductQuery.data?.forEach((saleByProduct) => {
            labels.push(saleByProduct?.product?.name);
            chartData.datasets[0].data.push(saleByProduct.productStoreCart._count.productStoreId)
        })
    }
    return (
        <>
            <Head>
                <title>Wapi - Reportes</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex justify-around w-full">
                <div>
                    <h2 className="text-2xl mb-4">Clientes</h2>
                    <Table table={customersTable} className='border border-1 border-black p-6' />
                </div>
                <div>
                    <h2 className="text-2xl" mb-4>Ventas x Producto</h2>
                    <Pie data={chartData} />
                </div>
            </div>
        </>
    );
};

Reports.getLayout = function getLayout(page) {
    return (
        <Dashboard>
            {page}
        </Dashboard>
    )
}

export const getServerSideProps: GetServerSideProps = async (ctx: GetServerSidePropsContext) => {
    const session = await getServerAuthSession(ctx);

    if (!session) {
        return {
            redirect: { destination: "/api/auth/signin", permanent: false },
        }
    }

    return {
        props: session
    }
}

export default Reports;