import { GetServerSideProps, GetServerSidePropsContext } from "next";
import Head from "next/head";
import Dashboard from "../components/layouts/Dashboard";
import { getServerAuthSession } from "../server/common/get-server-auth-session";
import { NextPageWithLayout } from "./_app";

const Reports: NextPageWithLayout = () => {
    return (
        <>
            <Head>
                <title>Wapi - Reportes</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-96 rounded-lg border-4 border-dashed border-gray-200" >
                Reports
            </div>
        </>
    );
};

Reports.getLayout = function getLayout(page) {
    return (
        <Dashboard>
            {page}
        </Dashboard>
    )
}

export const getServerSideProps: GetServerSideProps = async (ctx: GetServerSidePropsContext) => {
    const session = await getServerAuthSession(ctx);

    if (!session) {
        return {
            redirect: { destination: "/api/auth/signin", permanent: false },
        }
    }

    return {
        props: session
    }
}

export default Reports;